name: Torque API
version: "3.2"
slug: frigate
description: MQTT for Torque - HA Version
url: "https://github.com/jrich007/torque-api-main"
startup: application
boot: auto
#webui: "http://[HOST]:[PORT:5000]/"
#watchdog: "http://[HOST]:[PORT:5000]/"
ingress: true
ingress_port: 5000
ingress_entry: /
panel_admin: false
ports:
  8128/tcp: 8128
ports_description:
  8128/tcp: Main port from Torque
host_network: false
usb: false
tmpfs: true
full_access: false
environment:
  CONFIG_FILE: /config/config.json
options: {}
schema: {}
services:
  - "mqtt:need"
arch:
  - amd64
  - armv7
  - aarch64
map:
  - "media:rw"
  - "config:rw"